version: '1'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/code
      - ./backend/node_modules:/code/node_modules
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/code
      - ./frontend/node_modules:/code/node_modules